sudo: required

language: python

services:
  - docker

before_install:
- docker pull opencadc/astroquery:3.7-alpine
- docker pull opencadc/astroquery:2.7-alpine

script:
- docker run --rm -v $(pwd):/usr/src/app opencadc/astroquery:3.7-alpine python setup.py install
- docker run --rm -v $(pwd):/usr/src/app opencadc/astroquery:2.7-alpine python setup.py install
